import fs from 'node:fs'
import path from 'node:path'
import type { Metadata } from 'next'
import Link from 'next/link'
import SimpleMarkdown from '@/components/SimpleMarkdown'
import { REPO } from '@/lib/site'

// The committed Weekly Arena Reports (reports/YYYY-MM-DD.md, generated by
// pipeline/scripts/generate-weekly-report.ts), newest first, rendered inline via the tiny
// SimpleMarkdown component — no markdown dependency. Static by construction: the reports are
// files in the repo, read at build time. Tolerant-optional like every other data surface: no
// reports directory (or an empty one) renders an honest "none yet", never an error.

export const dynamic = 'force-static'

export const metadata: Metadata = {
  title: 'Weekly reports — Ultrametric',
  description:
    'Weekly Rankings Reports — the last 7 days of rank flips, Overall score movers, new rankings and close races, generated from the committed score history. Copy-paste ready for a newsletter.',
}

interface Report {
  /** YYYY-MM-DD, from the filename. */
  date: string
  markdown: string
}

function loadReports(): Report[] {
  const dir = path.join(process.cwd(), 'reports')
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .sort()
    .reverse()
    .map((f) => ({ date: f.slice(0, -3), markdown: fs.readFileSync(path.join(dir, f), 'utf8') }))
}

export default function ReportsPage() {
  const reports = loadReports()
  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <div>
        <p className="text-sm uppercase tracking-widest text-emerald-400">Weekly reports</p>
        <h1 className="font-display leading-[1.1] mt-1 text-3xl font-bold tracking-tight">The Weekly Rankings Report</h1>
        <p className="mt-2 max-w-2xl text-zinc-400">
          One generated markdown report per week — the biggest Overall score movers, rank flips, new rankings and
          products, and the current close races, all derived from the committed score history. Each report lives{' '}
          <a
            href={`https://github.com/${REPO}/tree/main/reports`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-emerald-300 underline decoration-emerald-400/40 underline-offset-2 hover:text-emerald-200"
          >
            in the repo
          </a>{' '}
          as plain markdown — copy-paste ready for a newsletter. The rolling view is the{' '}
          <Link href="/changelog" className="text-emerald-300 underline decoration-emerald-400/40 underline-offset-2 hover:text-emerald-200">
            changelog
          </Link>
          .
        </p>
      </div>

      {reports.length === 0 ? (
        <p className="text-sm italic text-zinc-500">No reports generated yet.</p>
      ) : (
        <div className="space-y-6">
          {reports.map((report) => (
            <article key={report.date} id={report.date} className="scroll-mt-4 rounded-xl border border-zinc-800 p-5">
              <SimpleMarkdown markdown={report.markdown} />
            </article>
          ))}
        </div>
      )}
    </div>
  )
}
