// GENERATED by scripts/generate-mcp-demo-calls.mjs — do not edit by hand; edit
// data/mcp-demo-calls.json (hand-curated, live-verified read-only tool calls) and re-run the
// script. The identical map is hardcoded as MCP_DEMO_CALLS in infra/cloudflare-proxy/worker.js
// (kept dependency-free on purpose); a unit test asserts the two never drift.
export interface McpDemoCall {
  /** Tool to call — a read-only, no-side-effect tool verified live before curation. */
  tool: string
  /** Canned safe arguments — the worker never accepts arguments from clients. */
  args: Record<string, unknown>
  /** Human label for the "run a real call" button. */
  label: string
}

export const MCP_DEMO_CALLS: Record<string, McpDemoCall> = {
  'auth-platforms/better-auth': { tool: "search_docs", args: {"query":"sign in with google"}, label: "search the Better Auth docs for \"sign in with google\"" },
  'self/productarena': { tool: "top_products", args: {"metric":"agentReady","limit":5}, label: "rank the top 5 agent-ready products across every ranking" },
  'voice-agents/retell': { tool: "list_api_endpoints", args: {}, label: "list every API endpoint the Retell server exposes" },
}

export function mcpDemoCallFor(category: string, productId: string): McpDemoCall | null {
  return MCP_DEMO_CALLS[`${category}/${productId}`] ?? null
}
